/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_billthefarmer_mididriver_NativeMidiDriver */

#ifndef _Included_org_catrobat_catroid_pocketmusic_mididriver_NativeMidiDriver
#define _Included_org_catrobat_catroid_pocketmusic_mididriver_NativeMidiDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_billthefarmer_mididriver_NativeMidiDriver
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_catrobat_catroid_pocketmusic_mididriver_NativeMidiDriver_init
  (JNIEnv *, jobject);

/*
 * Class:     org_billthefarmer_mididriver_NativeMidiDriver
 * Method:    config
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_catrobat_catroid_pocketmusic_mididriver_NativeMidiDriver_config
  (JNIEnv *, jobject);

/*
 * Class:     org_billthefarmer_mididriver_NativeMidiDriver
 * Method:    write
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_catrobat_catroid_pocketmusic_mididriver_NativeMidiDriver_write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_billthefarmer_mididriver_NativeMidiDriver
 * Method:    shutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_catrobat_catroid_pocketmusic_mididriver_NativeMidiDriver_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
