# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "1"
opt_out_usage

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "upload Catroid metadata only"
  lane :upload_Metadata_Catroid do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid',
      track:                      'alpha',
      json_key_data:              ENV['googlePlayJsonKey'],
      metadata_path:              './fastlane/metadata/android',
      skip_upload_apk:            'true',
      skip_upload_metadata:       'false',
      skip_upload_images:         'false',
      skip_upload_screenshots:    'false',
      validate_only:              'false',
      check_superseded_tracks:    'false',
    )
  end

  desc "upload Catroid APK to alpha track"
  lane :upload_APK_Catroid do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid',
      track:                      'alpha',
      json_key_data:              ENV['googlePlayJsonKey'],
      apk_paths:                  './catroid/build/outputs/apk/catroid/signedRelease/catroid-pocketCode-signedRelease.apk',
      skip_upload_apk:            'false',
      skip_upload_metadata:       'true',
      skip_upload_images:         'true',
      skip_upload_screenshots:    'true',
      validate_only:              'false',
      check_superseded_tracks:    'false',
    )
  end

  desc "promote Catroid APK on alpha track to production"
  lane :promote_Catroid do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid',
      track:                      'alpha',
      track_promote_to:           'production',
      json_key_data:              ENV['googlePlayJsonKey'],
      metadata_path:              './fastlane/metadata/android',
      skip_upload_apk:            'true',
      skip_upload_metadata:       'true',
      skip_upload_images:         'true',
      skip_upload_screenshots:    'true',
    )
  end

  desc "upload CreateAtSchool metadata only"
  lane :upload_Metadata_CreateAtSchool do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid.createatschool',
      track:                      'alpha',
      json_key_data:              ENV['googlePlayJsonKey'],
      metadata_path:              './fastlane/metadata/android',
      skip_upload_apk:            'true',
      skip_upload_metadata:       'false',
      skip_upload_images:         'false',
      skip_upload_screenshots:    'false',
      validate_only:              'false',
      check_superseded_tracks:    'false',
    )
  end

  desc "upload CreateAtSchool APK to alpha track"
  lane :upload_APK_CreateAtSchool do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid.createatschool',
      track:                      'alpha',
      json_key_data:              ENV['googlePlayJsonKey'],
      apk_paths:                  './catroid/build/outputs/apk/createatschool/signedRelease/catroid-createatschool-signedRelease.apk',
      skip_upload_apk:            'false',
      skip_upload_metadata:       'true',
      skip_upload_images:         'true',
      skip_upload_screenshots:    'true',
      validate_only:              'false',
      check_superseded_tracks:    'false',
    )
  end

  desc "promote CreateAtSchool APK on alpha track to production"
  lane :promote_CreateAtSchool do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid.createatschool',
      track:                      'alpha',
      track_promote_to:           'production',
      json_key_data:              ENV['googlePlayJsonKey'],
      metadata_path:              './fastlane/metadata/android',
      skip_upload_apk:            'true',
      skip_upload_metadata:       'true',
      skip_upload_images:         'true',
      skip_upload_screenshots:    'true',
    )
  end

  desc "upload EmbroideryDesigner metadata only"
    lane :upload_Metadata_EmbroideryDesigner do
      upload_to_play_store(
        package_name:               'org.catrobat.catroid.embroiderydesigner',
        track:                      'alpha',
        json_key_data:              ENV['googlePlayJsonKey'],
        metadata_path:              './fastlane/metadata/android',
        skip_upload_apk:            'true',
        skip_upload_metadata:       'false',
        skip_upload_images:         'false',
        skip_upload_screenshots:    'false',
        validate_only:              'false',
        check_superseded_tracks:    'false',
      )
    end

    desc "upload EmbroideryDesigner APK to alpha track"
    lane :upload_APK_EmbroideryDesigner do
      upload_to_play_store(
        package_name:               'org.catrobat.catroid.embroiderydesigner',
        track:                      'alpha',
        json_key_data:              ENV['googlePlayJsonKey'],
        apk_paths:                  './catroid/build/outputs/apk/embroiderydesigner/signedRelease/catroid-embroiderydesigner-signedRelease.apk',
        skip_upload_apk:            'false',
        skip_upload_metadata:       'true',
        skip_upload_images:         'true',
        skip_upload_screenshots:    'true',
        validate_only:              'false',
        check_superseded_tracks:    'false',
      )
    end

    desc "promote EmbroideryDesigner APK on alpha track to production"
    lane :promote_EmbroideryDesigner do
      upload_to_play_store(
        package_name:               'org.catrobat.catroid.embroiderydesigner',
        track:                      'alpha',
        track_promote_to:           'production',
        json_key_data:              ENV['googlePlayJsonKey'],
        metadata_path:              './fastlane/metadata/android',
        skip_upload_apk:            'true',
        skip_upload_metadata:       'true',
        skip_upload_images:         'true',
        skip_upload_screenshots:    'true',
      )
    end

  desc "upload Luna&Cat metadata only"
  lane :upload_Metadata_LunaAndCat do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid.lunaandcat',
      track:                      'alpha',
      json_key_data:              ENV['googlePlayJsonKey'],
      metadata_path:              './fastlane/metadata/android',
      skip_upload_apk:            'true',
      skip_upload_metadata:       'false',
      skip_upload_images:         'false',
      skip_upload_screenshots:    'false',
      validate_only:              'false',
      check_superseded_tracks:    'false',
    )
  end

  desc "upload Luna&Cat APK to alpha track"
  lane :upload_APK_LunaAndCat do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid.lunaandcat',
      track:                      'alpha',
      json_key_data:              ENV['googlePlayJsonKey'],
      apk_paths:                  './catroid/build/outputs/apk/lunaAndCat/signedRelease/catroid-lunaAndCat-signedRelease.apk',
      skip_upload_apk:            'false',
      skip_upload_metadata:       'true',
      skip_upload_images:         'true',
      skip_upload_screenshots:    'true',
      validate_only:              'false',
      check_superseded_tracks:    'false',
    )
  end

  desc "promote Luna&Cat APK on alpha track to production"
  lane :promote_LunaAndCat do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid.lunaandcat',
      track:                      'alpha',
      track_promote_to:           'production',
      json_key_data:              ENV['googlePlayJsonKey'],
      metadata_path:              './fastlane/metadata/android',
      skip_upload_apk:            'true',
      skip_upload_metadata:       'true',
      skip_upload_images:         'true',
      skip_upload_screenshots:    'true',
    )
  end

  desc "upload Phiro metadata only"
  lane :upload_Metadata_Phiro do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid.phiro',
      track:                      'alpha',
      json_key_data:              ENV['googlePlayJsonKey'],
      metadata_path:              './fastlane/metadata/android',
      skip_upload_apk:            'true',
      skip_upload_metadata:       'false',
      skip_upload_images:         'false',
      skip_upload_screenshots:    'false',
      validate_only:              'false',
      check_superseded_tracks:    'false',
    )
  end

  desc "upload Phiro APK to alpha track"
  lane :upload_APK_Phiro do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid.phiro',
      track:                      'alpha',
      json_key_data:              ENV['googlePlayJsonKey'],
      apk_paths:                  './catroid/build/outputs/apk/phiro/signedRelease/catroid-phiro-signedRelease.apk',
      skip_upload_apk:            'false',
      skip_upload_metadata:       'true',
      skip_upload_images:         'true',
      skip_upload_screenshots:    'true',
    )
  end

  desc "promote Phiro APK on alpha track to production"
  lane :promote_Phiro do
    upload_to_play_store(
      package_name:               'org.catrobat.catroid.phiro',
      track:                      'alpha',
      track_promote_to:           'production',
      json_key_data:              ENV['googlePlayJsonKey'],
      metadata_path:              './fastlane/metadata/android',
      skip_upload_apk:            'true',
      skip_upload_metadata:       'true',
      skip_upload_images:         'true',
      skip_upload_screenshots:    'true',
    )
  end

  desc "upload PocketCodeBeta metadata only"
    lane :upload_Metadata_PocketCodeBeta do
      upload_to_play_store(
        package_name:               'org.catrobat.catroid.test',
        track:                      'alpha',
        json_key_data:              ENV['googlePlayJsonKey'],
        metadata_path:              './fastlane/metadata/android',
        skip_upload_apk:            'true',
        skip_upload_metadata:       'false',
        skip_upload_images:         'false',
        skip_upload_screenshots:    'false',
        validate_only:              'false',
        check_superseded_tracks:    'false',
      )
    end

    desc "upload PocketCodeBeta APK to alpha track"
    lane :upload_APK_PocketCodeBeta do
      upload_to_play_store(
        package_name:               'org.catrobat.catroid.test',
        track:                      'alpha',
        json_key_data:              ENV['googlePlayJsonKey'],
        apk_paths:                  './catroid/build/outputs/apk/pocketcodebeta/signedRelease/catroid-pocketcodebeta-signedRelease.apk',
        skip_upload_apk:            'false',
        skip_upload_metadata:       'true',
        skip_upload_images:         'true',
        skip_upload_screenshots:    'true',
        validate_only:              'false',
        check_superseded_tracks:    'false',
      )
    end

    desc "upload Mindstorms metadata only"
        lane :upload_Metadata_Mindstorms do
          upload_to_play_store(
            package_name:               'org.catrobat.catroid.mindstorms',
            track:                      'alpha',
            json_key_data:              ENV['googlePlayJsonKey'],
            metadata_path:              './fastlane/metadata/android',
            skip_upload_apk:            'true',
            skip_upload_metadata:       'false',
            skip_upload_images:         'false',
            skip_upload_screenshots:    'false',
            validate_only:              'false',
            check_superseded_tracks:    'false',
          )
        end

        desc "upload Mindstorms APK to alpha track"
        lane :upload_APK_Mindstorms do
          upload_to_play_store(
            package_name:               'org.catrobat.catroid.mindstorms',
            track:                      'alpha',
            json_key_data:              ENV['googlePlayJsonKey'],
            apk_paths:                  './catroid/build/outputs/apk/mindstorms/signedRelease/catroid-mindstorms-signedRelease.apk',
            skip_upload_apk:            'false',
            skip_upload_metadata:       'true',
            skip_upload_images:         'true',
            skip_upload_screenshots:    'true',
            validate_only:              'false',
            check_superseded_tracks:    'false',
          )
        end

        desc "promote Mindstorms APK on alpha track to production"
        lane :promote_Mindstorms do
          upload_to_play_store(
            package_name:               'org.catrobat.catroid.mindstorms',
            track:                      'alpha',
            track_promote_to:           'production',
            json_key_data:              ENV['googlePlayJsonKey'],
            metadata_path:              './fastlane/metadata/android',
            skip_upload_apk:            'true',
            skip_upload_metadata:       'true',
            skip_upload_images:         'true',
            skip_upload_screenshots:    'true',
          )
        end
end
