#!/usr/bin/env python3

import os
import sys

os.environ['SCRIPT_DIR'] = os.path.dirname(os.path.realpath(__file__))
os.environ['REPO_DIR'] = os.path.realpath(os.path.join(os.environ['SCRIPT_DIR'], ".."))

import build_helper_functions

def usage():
    print(sys.argv[0] + """

Validates and if neccessary installs the Android SDK in ANDROID_SDK_ROOT.

The environment variable ANDROID_SDK_ROOT needs to be set.""")

build_helper_functions.check_number_of_parameters(valid_param_count=0, usage_func=usage)

build_helper_functions.setup_android_sdk()
