#!/usr/bin/env python3

import os
import sys
import subprocess

os.environ['SCRIPT_DIR'] = os.path.dirname(os.path.realpath(__file__))
os.environ['REPO_DIR'] = os.path.realpath(os.path.join(os.environ['SCRIPT_DIR'], ".."))

import build_helper_functions

def usage():
    print(sys.argv[0] + """

Start the emulator, if none exists, create on.

The environment variable ANDROID_SDK_ROOT needs to be set.""")

build_helper_functions.check_number_of_parameters(valid_param_count=0, usage_func=usage)

return_code = build_helper_functions.bring_emulator_in_running_state()

sys.exit(return_code)
