#!/usr/bin/env python3

import os
import sys
import subprocess

os.environ['SCRIPT_DIR'] = os.path.dirname(os.path.realpath(__file__))
os.environ['REPO_DIR'] = os.path.realpath(os.path.join(os.environ['SCRIPT_DIR'], ".."))

import build_helper_functions

def usage():
    print(sys.argv[0] + """ <test_filter>

This scripts runs all the local unit tests for the debug flavor.
A filter can be passed as single argument which is then passed as
'--tests <filter>' parameter.
See: https://docs.gradle.org/current/userguide/java_testing.html#test_filtering

The environment variable ANDROID_SDK_ROOT needs to be set.""")

build_helper_functions.check_number_of_parameters(valid_param_count_min=0, valid_param_count_max=1, usage_func=usage)

## RUN tests
test_runner_cmd = [ build_helper_functions.get_relative_gradle_name(), 'clean', 'testCatroidDebug' ]
## pass filter if argument is given
if len(sys.argv) > 1:
    test_runner_cmd = test_runner_cmd + [ '--tests', sys.argv[1] ]

print("Calling: " + " ".join(test_runner_cmd))
return_code = subprocess.run( test_runner_cmd, cwd=os.environ['REPO_DIR'] ).returncode
sys.exit(return_code)
