#!/usr/bin/env python3

import os
import sys
import subprocess

os.environ['SCRIPT_DIR'] = os.path.dirname(os.path.realpath(__file__))
os.environ['REPO_DIR'] = os.path.realpath(os.path.join(os.environ['SCRIPT_DIR'], ".."))

import build_helper_functions

def usage():
    print(sys.argv[0] + """

Stop the emulator which was started by the helper scripts.

The environment variable ANDROID_SDK_ROOT needs to be set.

Be aware that Jenkins cleans the workspace before every build, this can
be partly replicated by './gradlew clean'.""")

build_helper_functions.check_number_of_parameters(valid_param_count=0, usage_func=usage)

stop_emulator_cmd = build_helper_functions.get_jenkins_android_helper_executable('jenkins_android_emulator_helper') + [ '-K' ]

print("Calling: " + " ".join(stop_emulator_cmd))
subprocess.run( stop_emulator_cmd, cwd=os.environ['REPO_DIR'] )
