#!/usr/bin/env python3

import os
import sys
import subprocess

os.environ['SCRIPT_DIR'] = os.path.dirname(os.path.realpath(__file__))
os.environ['REPO_DIR'] = os.path.realpath(os.path.join(os.environ['SCRIPT_DIR'], ".."))

import build_helper_functions

def usage():
    print(sys.argv[0] + """

This script is a simple wrapper for the build_helper_run_tests_on_emulator which runs
with an defined parameter to test the package org.catrobat.catroid.test

The environment variable ANDROID_SDK_ROOT needs to be set.""")

build_helper_functions.check_number_of_parameters(valid_param_count=0, usage_func=usage)

# Run Unit and device tests for package: org.catrobat.catroid.test
test_runner_cmd = build_helper_functions.get_build_scripts_executable('build_helper_run_tests_on_emulator') + [ 'org.catrobat.catroid.test' ]

print("Calling: " + " ".join(test_runner_cmd))
return_code = subprocess.run( test_runner_cmd ).returncode
sys.exit(return_code)
