name: 'Test Report'

on:
  workflow_run:
    workflows:
      - Catroid Main Workflow
      - Catroid UI Test Workflow
    types:
      - completed

concurrency:
  group: reporter-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2
        with:
          artifact: /(.*)-test-results-xml/     # artifact name
          name: JUnit $1 Tests               # Name of the check run which will be created
          path: '**/TEST-*.xml'             # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results